package ma.ensa.project.entity;

public enum PermissionEnum {
    CREATE_USER, READ_USER, UPDATE_USER,
    DELETE_USER,CREATE_CLIENT, READ_CLIENT,
    UPDATE_CLIENT, DELETE_CLIENT,CREATE_COMMANDE,
    READ_COMMANDE, UPDATE_COMMANDE, DELETE_COMMANDE,
    CREATE_PRODUIT, READ_PRODUIT, UPDATE_PRODUIT,
    DELETE_PRODUIT,CREATE_FACTURE, READ_FACTURE,
    UPDATE_FACTURE, DELETE_FACTURE,CREATE_PAIEMENT,
    READ_PAIEMENT, UPDATE_PAIEMENT, DELETE_PAIEMENT,
    MAIL;

}
